import json

data = {
    "name": "GitHub Actions",
    "description": "This JSON file was generated by a Python script within a GitHub Actions workflow."
}

with open("output.json", "w") as f:
    json.dump(data, f, indent=4)
