name: Build and Save Cheerio for JSBox

on:
  schedule:
    - cron: "0 0 * * *" # 每天运行一次（可根据需要调整）
  workflow_dispatch: # 手动触发

jobs:
  build-cheerio:
    runs-on: ubuntu-latest

    steps:
    # 1. 检出代码仓库（必要）
    - name: Checkout the repository
      uses: actions/checkout@v3

    # 2. 下载 Cheerio 最新源码
    - name: Download Cheerio source
      run: |
        git clone --depth=1 https://github.com/cheeriojs/cheerio.git cheerio-latest

    # 3. 设置 Node.js 环境
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    # 4. 安装依赖并构建
    - name: Install and Build Cheerio
      working-directory: cheerio-latest
      run: |
        npm install
        npm run build # 生成 dist 文件
        ls -alh dist/ # 查看 dist 文件夹的内容，确认构建文件是否存在

    # 5. 保存构建文件为 Artifact
    - name: Upload Cheerio for JSBox
      uses: actions/upload-artifact@v3
      with:
        name: cheerio-jsbox
        path: cheerio-latest/dist/
