name: Fetch and Split Subscriptions

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 3 * * *'
jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install aiohttp requests

      - name: Run fetch script
        run: python fetch_subscriptions.py

      - name: Commit and push files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          # 添加所有订阅文件和信息文件
          git add subscriptions_*.txt
          git add SUBSCRIPTIONS_INFO.md
          
          # 清理旧文件
          if [ -f "merged_subscriptions.txt" ]; then
            git rm merged_subscriptions.txt
          fi
          
          git diff --cached --quiet || git commit -m "更新订阅文件"
          git push origin main
