name: Fetch and Merge Subscriptions

on:
  schedule:
    - cron: '0 0 * * *'  # 每天UTC时间午夜运行
  workflow_dispatch:      # 允许手动触发

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install aiohttp requests

      - name: Run fetch script
        run: python fetch_subscriptions.py


